export const quips = {
  undoChurn: [
    "Ctrl+Z is tired. Your code? Not so much. Carry on, champion of circles.",
    "That's some impressive digital yo-yo action right there.",
    "Undo, redo, repeat. The sacred dance of indecision continues.",
    "Your keyboard's Z key is filing for workers' compensation.",
    "Achievement unlocked: Master of the Eternal Loop. Population: you.",
    "Plot twist: the code was fine the first time. But who's counting?",
    "Professional indecision at its finest. Your code editor is getting dizzy.",
    "That's what we call the 'developer's dilemma' - perfection through repetition.",
    "Why commit to anything when you can just keep undoing? Life philosophy right there.",
    "Your code is experiencing an identity crisis. Very relatable, honestly.",
    "Ctrl+Z: the closest thing to time travel. Use it wisely... or don't.",
    "Fun fact: You've undone more work than most people do in a day. Impressive!",
    "The art of coding backwards. You're basically a reverse engineer now.",
  ],

  netZero: [
    "You typed, you untyped, you conquered absolutely nothing. Iconic.",
    "Full circle back to square one. That's some philosophical coding right there.",
    "Net progress: zero. Net entertainment value: priceless.",
    "Like a digital boomerang, but less productive.",
    "You've successfully achieved quantum coding - existing in all states simultaneously.",
    "The code that was, is, and shall be again. Very zen.",
    "Achievement unlocked: Time Lord. You've mastered the art of temporal coding.",
    "Your code just experienced déjà vu. Again.",
    "Congratulations! You've invented the coding equivalent of a hamster wheel.",
    "Your progress bar is stuck at 0%. That's actually kind of impressive.",
    "You've mastered the ancient art of productive procrastination. Sensei level.",
    "Plot twist: The real code was the friends we made along the way. Oh wait...",
    "You're not coding, you're performance art. Very avant-garde.",
  ],

  uiFiddle: [
    "New theme, same vibes. Procrastination now in Dark+.",
    "Rearranging deck chairs on the Titanic, but make it aesthetic.",
    "Perfect UI setup achieved. Time to code? Nah, let's tweak it more.",
    "Your IDE is now 2% more beautiful and 0% more productive. Worth it.",
    "Marie Kondo would be proud of all this interface organizing.",
    "The real code was the themes we toggled along the way.",
    "Professional procrastination: when changing settings becomes an art form.",
    "Your IDE has never looked better. Your deadline, however...",
    "Why write code when you can make the editor look pretty? Priorities!",
    "Your customization skills are off the charts. Your actual coding skills... TBD.",
    "Fun fact: You've spent more time on UI than actual functionality. Classic!",
    "Your IDE is now perfectly optimized for... more procrastination. Well done!",
    "Breaking news: Local developer discovers 47 new ways to avoid coding.",
    "You're not procrastinating, you're 'optimizing your development environment.'",
  ],

  tabSwitch: [
    "Alt+Tab cardio complete. Hydrate. Then… continue not coding.",
    "Tab surfing champion reporting for duty. Waves are looking good today.",
    "That's some Olympic-level tab gymnastics right there.",
    "Internet successfully checked. All tabs accounted for. Panic averted.",
    "Professional multitasker at work. The task? Avoiding the actual task.",
    "Your browser tabs are a monument to possibility and procrastination.",
    "Context switching level: Expert. Code completion level: Beginner.",
    "You've just toured the entire internet. Twice. Impressive dedication.",
    "Quick! Check Instagram reels. Your code will still be broken when you get back.",
    "Those TikTok videos won't watch themselves. Priorities, people!",
    "Breaking: Local developer discovers YouTube has new content. Shocking!",
    "Your attention span just set a new record. For shortest duration ever.",
    "Fun fact: You've visited more websites than lines of code written today.",
    "Why focus on one thing when you can poorly focus on everything?",
    "Your browser history is more interesting than your commit history.",
    "Plot twist: The real productivity was the memes we saw along the way.",
  ],

  warmUp: [
    "Pre-game stretches taking longer than the game. Olympic level.",
    "Thorough preparation is key. Or maybe you just got distracted. Both valid.",
    "That was some serious contemplation time. The code appreciates the buildup.",
    "Slow and steady wins the... actually, just slow. But that's fine too.",
    "Extended warm-up complete. Your keyboard is now properly seasoned.",
    "The dramatic pause before coding. Like a pianist before a concert.",
    "Professional staring contest with your screen. You're winning so far.",
    "Meditation phase complete. Enlightenment phase... still loading.",
    "Why rush into coding when you can savor this moment of pure potential?",
    "Your warm-up routine is longer than most people's actual work sessions.",
    "Fun fact: You've been 'about to start' for longer than most movies.",
    "The anticipation is killing everyone. Mostly your deadline.",
    "Your keyboard is getting cold from lack of use. Maybe warm it up... later.",
    "Breaking: Local developer still preparing to prepare. More at 11.",
  ],

  idle: [
    "Screen: on. Ambition: off. Perfect balance restored.",
    "Achieving zen through strategic inactivity. Mindfulness level: expert.",
    "Your cursor is blinking hopefully. It believes in you more than you do.",
    "Professional staring contest with your code. Current score: Code 1, You 0.",
    "Taking 'think before you code' to new philosophical heights.",
    "The code is patiently waiting. It's very understanding about these things.",
    "Power save mode: activated. Productivity mode: still buffering.",
    "You've entered the contemplation zone. Population: you and your cursor.",
    "Your screen saver is more active than you are right now. Impressive!",
    "Fun fact: You're burning more calories breathing than coding. Efficient!",
    "Your code is aging like fine wine. Very, very slowly.",
    "Breaking: Local developer discovers the art of doing absolutely nothing.",
    "Your productivity level has reached new lows. That's... actually impressive?",
    "Why code when you can just exist? Very philosophical approach.",
    "Your cursor is having an existential crisis. It forgot what it's for.",
    "Plot twist: Maybe the real code was the time we wasted along the way.",
  ],
};

export const getRandomQuip = (type: keyof typeof quips): string => {
  const messages = quips[type];
  return messages[Math.floor(Math.random() * messages.length)];
};